### ISSUE TITLE
internal port routing possible?

### ISSUE THREAD

**Issue by patrikdolsson** [wfg/docker-wireguard#2]
I've got two containers running the same image that has a hardcoded port that I can't change. I want to be able to expose these ports to the host, the problem with this is that both containers use the same internal port that would then be exposed through the vpn container.

I just wanted to ask for some ideas to solve this. Would it be possible to route one of the containers through a middleman container that routes the open port to another? How would one write the dockerfile and scripts for that if that's possible? Any other ideas?

for full transparency I am running a fork of [wfg/docker-openvpn-client](https://github.com/wfg/docker-openvpn-client). But the issue should be the same with this project.

**Comment by wfg** [comment]
I'd suggest trying to change the listening port of one of your applications. AFAIK the middle-man container in your idea would just be an iptables/nftables rule, but I don't know how it would look.

Either way, there's nothing I can do about it in my image, so I'm going to close this issue.
